name: Cypress Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests
        run: |
          npm run cypress:run